### ISSUE TITLE
Error running Classified.generate_fake() method

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [ukgovdatascience/classifyintentsapp#123]
When running `Classified.generate_fake()` on the remote instance, the following error is thrown:
```
cap@79c2fc67-f06e-4937-7c9c-217a:~/app$ python manage.py populate
Traceback (most recent call last):
  File "manage.py", line 122, in <module>
    manager.run()
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 119, in populate
    Classified.generate_fake(500, 10)
  File "/home/vcap/app/app/models.py", line 285, in generate_fake
    code_id=int(choice(c_ids)),
  File "mtrand.pyx", line 1110, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17158)
ValueError: a must be non-empty
```

In addition, codes and project codes are not shown on the surveys page:

![image](https://user-images.githubusercontent.com/4583655/31720617-f4b593d4-b40e-11e7-9397-9a81e53af0ef.png)

This is despite the codes having been produced, and visible on the codes page:

 
![image](https://user-images.githubusercontent.com/4583655/31720635-0596e4fa-b40f-11e7-8e89-f3c51c8da174.png)

**Comment by ivyleavedtoadflax** [comment]
```codes = Codes.query.filter(Codes.end_date is None).all()```

should be:

```codes = Codes.query.filter(Codes.end_date.is_(None)).all()```

http://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.is_
